In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.svm import SVC 

In [ ]:
data = np.array(pd.read_csv("Test_Fundus.csv"))

In [ ]:
y = data[:,0]
X = data[:,1:]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 314) 

In [ ]:
svm_model_linear = SVC(kernel = 'linear', class_weight = 'balanced').fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test) 

In [ ]:
accuracy = svm_model_linear.score(X_test, y_test)

In [ ]:
cm = confusion_matrix(y_test, svm_predictions) 

In [ ]:
print(cm)

[[5 1 0]
 [1 4 1]
 [0 0 3]]


In [ ]:
print(accuracy)

0.8
